In [1]:
import numpy as np
import pandas as pd
import os
import time
import datetime
import re

In [2]:
os.chdir(u'D:\\Terry\\工作文件\\氣象局計畫\\資料')
os.getcwd()

'D:\\Terry\\工作文件\\氣象局計畫\\資料'

In [5]:
banana = pd.read_csv('香蕉災損資料\\山坡地比例\\banana.csv',engine='python')
town_code = pd.read_excel('香蕉災損資料\\山坡地比例\\鄉鎮界.xlsx')

In [14]:
banana

,Area,TOWNID,TOWNCODE,TOWNENG,COUNTYID,COUNTYCODE,_count,_2count,per
0,7.178542e+05,P09,1000909.0,Citong Township,P,10009,15.258650,1830.036039,0.008338
1,1.220285e+06,M01,1000801.0,Nantou City,M,10008,523.769782,3108.117388,0.168517
2,4.062886e+04,D10,6700002.0,Yanshui District,D,67000,0.868394,113.567624,0.007646
3,1.660259e+05,D33,6700028.0,Guiren District,D,67000,22.287494,455.259927,0.048956
4,4.046834e+04,N23,1000723.0,Fangyuan Township,N,10007,0.006998,112.628013,0.000062
...,...,...,...,...,...,...,...,...,...
300,1.786442e+05,U09,1001509.0,Ruisui Township,U,10015,79.922891,465.381582,0.171736
301,1.902145e+05,N07,1000712.0,Tianzhong Township,N,10007,8.993755,480.313148,0.018725
302,5.675650e+04,N03,1000703.0,Hemei Township,N,10007,1.374417,154.976085,0.008869
303,1.672116e+03,F08,6500019.0,Shiding District,F,65000,4.114942,4.180290,0.984368
304,1.540540e+05,K04,1000509.0,Gongguan Township,K,10005,242.671044,412.117036,0.588840

In [12]:
town_code

       townid  towncode countyname townname
0    65000071   6500025        新北市      雙溪區
1    64000036   6400016        高雄市      大社區
2    10009004   1000913        雲林縣      麥寮鄉
3    67000017   6700019        臺南市      善化區
4    67000018   6700023        臺南市      玉井區
..        ...       ...        ...      ...
608  10007024   1000719        彰化縣      北斗鎮
611  10007028   1000712        彰化縣      田中鎮
613  10007029   1000725        彰化縣      竹塘鄉
614  10007031   1000718        彰化縣      二水鄉
615  10007032   1000702        彰化縣      鹿港鎮

[352 rows x 4 columns]

In [11]:
town_code = town_code.drop_duplicates('towncode')
banana['TOWNCODE']/=10

In [17]:
df = banana.merge(town_code[['towncode','countyname','townname']],left_on='TOWNCODE',right_on='towncode',how='left')
df.drop('towncode',axis=1,inplace=True)

In [19]:
df.to_excel('香蕉災損資料\\山坡地比例\\香蕉坡地比例.xlsx')